services:
  app:
    container_name: breaderos_app
    build: .
    environment:
      BOOKS_ROOT: /opt/breaderos/static/books
    expose:
      - "5000"
    volumes:
      - ${BOOKS_HOST_PATH:-./static/books}:/opt/breaderos/static/books:rw
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: breaderos_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/css:/srv/static/css:ro
      - ./static/js:/srv/static/js:ro

    depends_on:
      - app
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
