events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream flask_app {
        server app:5000;
    }

    server {
        listen 80;
        server_name _;

        # Максимальний розмір запиту (на випадок великих html / відео)
        client_max_body_size 100M;

        # Статика JS / CSS / pictures (швидко, без Flask)
        location /static/ {
            alias /srv/static/;
            expires 7d;
            access_log off;
        }

        # Статика Books
        location /books/ {
            alias /opt/breaderos/static/books/;
            autoindex off;
            expires 7d;
        }

        # Усі інші запити → Gunicorn
        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # iframe / book pages
            proxy_buffering off;
        }
    }
}
